feat(dynamic): update consumer web and add dynamic fields
Tracktor/treege-consumer pull request #19
Opened 2024-03-18 15:36 UTC by graffkevin

2024-03-25 12:14 UTC, MickaelAustoni requested changes

2024-03-25 12:14 UTC, MickaelAustoni commented on README.md
> +    - [Provide tree basicExample](#Provide-tree-data)
Il faudrait laisser `data` car le but c'est de faire comprendre que c'est les data retourné par le consumer. L'exemple est only pour les dev qui consomme la librairie. Il y a un fichier spécifique pour les dev contributeur `CONTRIBUTING.md`

2024-03-25 12:14 UTC, MickaelAustoni commented on example/App.tsx
> +  Authorization: `Bearer ${await getApiAccessToken("arsene.lupin@tracktor.fr", "TestPassword!2023")}`,
Tu peux pas laisser ça en dur, c'est une lib public open source. Il faut soit mettre un example public avec une api placeholder, ou des data mocké ou soit config des var d'env spécifique pour notre cas. Moi je mockerais des data perso pour l'example.

2024-03-25 12:14 UTC, MickaelAustoni commented on src/components/Inputs/DynamicSelect/DynamicSelect.tsx
> +// import ControlledToolTip from "@/components/ControlledToolTip/ControlledToolTip";
A supprimer

2024-03-25 12:14 UTC, MickaelAustoni commented on src/components/Inputs/DynamicSelect/DynamicSelect.tsx
> +        <InputLabel id={`label-${name}`} shrink>
J'ai un peu regarder et on va virer le `shrink` et aussi sur le `Select` stp. Désoler avec ce shrink lol ! Je sais pas pourquoi on l'avait mis sur le select mais je vois pas de raison.

2024-03-25 12:14 UTC, MickaelAustoni commented on src/components/Inputs/DynamicSelect/DynamicSelect.tsx
> +  const [multipleOptions, setMultipleOptions] = useState<string[]>([""]);
Ici il faudrait un array vide `[]` à la place de `[""]` car sinon tu active le shrink sur l'option par défaut alors qu'aucune options est sélectionné. Tu n'aura pas le problème de uncontrolled/controlled car ta value existe quand même par défaut, elle est pas `undefined`

```suggestion
  const [multipleOptions, setMultipleOptions] = useState<string[]>([]);
```

2024-03-25 12:14 UTC, MickaelAustoni commented on src/components/Inputs/Select/Select.tsx
>    SelectChangeEvent,
Du coup dans le select supprimer aussi le `shrink`

2024-03-25 12:14 UTC, MickaelAustoni commented on src/components/Inputs/DateRange/DateRange.tsx
> +        // children,
Commentaire à supprimer stp

2024-03-25 12:14 UTC, MickaelAustoni commented on public/favicon.svg
Yeaahh magnifique 🤩

2024-03-25 12:14 UTC, MickaelAustoni commented on src/components/ControlledToolTip/ControlledToolTip.tsx
> +import { Tooltip, TooltipProps } from "@tracktor/design-system";
Il faudrait mettre: 
-  `ControlledToolTip` dans un dossier `DataDisplay`
-  `FieldFactory` dans le dossier `Inputs`
- `FormValidation` dans le dossier `Inputs` ou créer un dossier Form (au choix)

2024-03-25 12:14 UTC, MickaelAustoni commented on src/main.ts
> -export { default as TreegeValuesConsumer } from "@/features/TreegeValuesConsumer";
Attention `TreegeValuesConsumer` est utiliser dans ops tu peux pas le supprimer de l'export ! Il faut garder son nom et l'export ou si tu décide de la rename il faut l'export et ensuite il faudra update ops quand la nouvelle version du consumer sera ready

2024-03-25 12:14 UTC, MickaelAustoni commented on src/components/Inputs/DynamicSelect/useDynamicSelect.ts
> +    queryFn: () =>
Il manque le signal, très important pour éviter les query mulptiple

2024-03-25 12:14 UTC, MickaelAustoni commented on src/utils/getValueFromTree/getValueFromTree.ts
> +const getValueFromTree = (
Humm le nom est pas raccord avec ce que fait la fonction.  Ça laisse croire que tu récup des values depuis un arbre. Ça serait plutôt `getFormValueFromName` ?

2024-03-26 09:34 UTC, graffkevin commented on README.md
> +    - [Provide tree basicExample](#Provide-tree-data)
je pense c'est une modification automatique quand j'ai bougé/modifié les fichiers. J'ai remis data

2024-03-26 09:40 UTC, graffkevin commented on src/components/Inputs/DynamicSelect/DynamicSelect.tsx
> +// import ControlledToolTip from "@/components/ControlledToolTip/ControlledToolTip";
yes oubli de ma part

2024-03-26 09:41 UTC, graffkevin commented on src/components/Inputs/DynamicSelect/DynamicSelect.tsx
> +        <InputLabel id={`label-${name}`} shrink>
shrink supprimé dans Select et DynamicSelect

2024-03-26 09:44 UTC, graffkevin commented on src/components/Inputs/DynamicSelect/DynamicSelect.tsx
> +  const [multipleOptions, setMultipleOptions] = useState<string[]>([""]);
effectivement ca marche mieux comme ca :) 
<img width="390" alt="Capture d’écran 2024-03-26 à 10 44 38" src="https://github.com/Tracktor/treege-consumer/assets/51543682/aa5caa42-9d92-4e65-b0fb-bbcd72c6c1da">

2024-03-26 09:45 UTC, graffkevin commented on src/components/Inputs/Select/Select.tsx
>    SelectChangeEvent,
ouais fait

2024-03-26 09:51 UTC, graffkevin commented on src/components/ControlledToolTip/ControlledToolTip.tsx
> +import { Tooltip, TooltipProps } from "@tracktor/design-system";
j'ai ms ControlledToolTip dans DataDisplay / FieldFactory dans Inputs / FormValidation dans un nouveau dossier Form pour pas trop charger Inputs

2024-03-26 10:14 UTC, graffkevin commented on src/components/Inputs/DynamicSelect/useDynamicSelect.ts
> +    queryFn: () =>
j'ai ajouté le signal dans le fetch
```TS
  const { data, isError, isLoading } = useQuery({
    enabled: enableQuery,
    queryFn: ({signal}) =>
      fetch(updatedUrl, {...requestOptions, signal})
        .then((response) => {
          if (!response.ok) {
            throw new Error("Error fetching data");
          }
          return response.json();
        })
        .then((responseData) => responseData)
        .catch((error) => {
          throw new Error("Fetch error:", error);
        }),
    queryKey: [name, getValueFromParent],
  });
  ```

2024-03-26 10:18 UTC, graffkevin commented on src/utils/getValueFromTree/getValueFromTree.ts
> +const getValueFromTree = (
oui c'est plus parlant j'ai fais la modif

2024-03-26 11:43 UTC, graffkevin commented on README.md
> +    - [Provide tree basicExample](#Provide-tree-data)
j'ai juste roll back avec l'original du coup comme treegeValueConsumer est de nouveau la

2024-03-26 11:44 UTC, graffkevin commented on src/main.ts
> -export { default as TreegeValuesConsumer } from "@/features/TreegeValuesConsumer";
j'ai remis TreegeValuesConsumer pour ne pas avoir de breaking change et j'ai adapté dans example

2024-03-26 11:44 UTC, graffkevin commented on example/App.tsx
> +  Authorization: `Bearer ${await getApiAccessToken("arsene.lupin@tracktor.fr", "TestPassword!2023")}`,
je l'ai viré et mis basic example

2024-03-26 14:39 UTC, MickaelAustoni approved these changes

2024-03-26 14:39 UTC, merged