feat/update form
Tracktor/treege-consumer pull request #21
Opened 2024-04-02 08:25 UTC by badreleglil

2024-04-04 13:27 UTC, MickaelAustoni requested changes

2024-04-04 13:27 UTC, MickaelAustoni commented on example/App.tsx
> +const API_TOKEN = "YOUR_API_TOKEN";
Le consumer est open source et il est pas fait pour utiliser notre api en exemple. L'exemple dois être générique sans call api. Kevin avait fait exactement la même chose que toi lol.

2024-04-04 13:27 UTC, MickaelAustoni commented on example/data/basicExample.ts
>  const basicExample = {
Pareil dois y avoir des chose à rollback ici du coup

2024-04-04 13:27 UTC, MickaelAustoni commented on example/data/basicJsonValues.ts
> +const basicJsonValues = [
ici aussi pour le rollback

2024-04-04 13:27 UTC, MickaelAustoni commented on src/features/TreegeConsumer/TreegeConsumer.tsx
> +  renderInput,
Une bonne pratique ne JS c'est de mettre toujours les valeurs par default à la fin.  ex :

```
  ...
  isLoadingFormValidation,
  jsonInitialValues,
  renderInput,
  variant = "standard",
  dataFormatOnSubmit = "json",
```

2024-04-04 13:27 UTC, MickaelAustoni commented on src/features/TreegeConsumer/TreegeConsumer.tsx
> +  renderInput?(input: JsonFormValue): ReactElement | undefined;
`renderInputs` plutôt non ? Et tu peux ajouter un exemple d'usage dans ton commentaire stp un truc du genre : 

``` tsx
  /**
   * Render custom render input value ()
   * <TreegeConsumer renderInput={(input) => <CustomInput input={input} />} />
   */
```

2024-04-04 13:27 UTC, MickaelAustoni commented on src/features/TreegeConsumer/TreegeConsumer.tsx
> +  jsonInitialValues?: JsonFormValue[];
Humm pour simplifier l'usage du composant, j'aurais plutôt ajouté le type dans `initialValues` qui est déjà existant et tu check juste si c'est un array ou pas. Du genre : 

``` tsx
  initialValues?:
    | {
        [key: string]: unknown;
      }
    | JsonFormValue[];
```

2024-04-04 13:27 UTC, MickaelAustoni commented on src/features/TreegeConsumer/TreegeConsumer.tsx
> +  if (isCustomRenderInput) {
Nice le render props, te voila un nouveau pattern appris 💪

2024-04-04 14:29 UTC, MickaelAustoni requested changes

2024-04-04 14:29 UTC, MickaelAustoni commented on src/utils/setInitialJsonValues/setInitialJsonValues.ts
> + * Prefixes the name of each field in the array with the tree path.
Résidu de copier/coller le commentaire 😅

2024-04-04 14:29 UTC, MickaelAustoni commented on src/utils/setInitialJsonValues/setInitialJsonValues.ts
> +const setInitialJsonValues = (jsonFormValues?: JsonFormValue[]): FieldValues | undefined =>
Plutôt `initializeFieldValuesFromJson` non ?

2024-04-04 14:29 UTC, MickaelAustoni commented on src/features/TreegeConsumer/useTreegeConsumer.ts
> +  }, [jsonInitialValues]);
```suggestion
  useEffect(() => {
    const initialFieldValues = initializeFieldValuesFromJson(jsonInitialValues);

    if (initialFieldValues) {
      setFieldValues(initialFieldValues);
    }
  }, [jsonInitialValues]);
```

2024-04-04 14:29 UTC, MickaelAustoni commented on src/components/Inputs/BooleanField/BooleanField.tsx
> +  handleFormValue?(dataAttribute: ChangeEventField): void;
Ici c'est pas un handler mais un event donc ici je verrais plutôt onChange tout simplement. Et pareil pour les autre champs. Et dans `useTreegeConsumer` par contre c'est un handler donc je verrais bien   `const handleChangeFormValue = (dataAttribute: ChangeEventField): void => {`

2024-04-04 14:29 UTC, MickaelAustoni commented on src/components/Inputs/DynamicSelect/DynamicSelect.tsx
> +  const checkIfObjectAsKey = (obj: unknown, key: string) => {
Cette fonction est utilisé à plusieurs endroit et fait exactement la même chose. En plus sont nom est franchement pas ouf. Plutôt `getObjectValueByKey`  or `safeGetObjectValueByKey`

2024-04-04 14:29 UTC, MickaelAustoni commented on src/components/Inputs/HiddenField/HiddenField.tsx
> +  return <input type="hidden" name={name} value={IsString(value) ? value : ""} />;
Ici tu pourrais faire ça je pense

```suggestion
  return <TextField type="hidden" name={name} value={value}  />;
```

2024-04-04 14:29 UTC, MickaelAustoni commented on src/components/Inputs/Select/Select.tsx
> +    // eslint-disable-next-line
Frerooooooooo !!! Frerooooooooo !!! Tu peux pas me laisser tu me connais jamais de la vie ça 😅😅😅😅😅😅
Ce code à mon avis ne fonctionne pas si tu change les value dynamiquement (si dans l'example tu vient copier/coller une autre valeur avec des champs inititial)

2024-04-04 14:29 UTC, MickaelAustoni commented on src/components/Inputs/Select/Select.tsx
> +        value={value || ""}
```suggestion
        value={value}
```

2024-04-04 14:29 UTC, MickaelAustoni commented on src/components/Inputs/Select/Select.tsx
> +const Select = ({ data, helperText, inputRef, required, handleFormValue, readOnly, value }: SelectProps, ref: Ref<HTMLDivElement>) => {
Ici tu peux initialiser à string vide directement dans la props en param. D'ailleurs tu peux le faire à tous les champs je pense pour éviter d'avoir l'erreur react controller/uncontrolled

```suggestion
const Select = ({ data, helperText, inputRef, required, handleFormValue, readOnly, value = "" }: SelectProps, ref: Ref<HTMLDivElement>) => {
```

2024-04-04 14:45 UTC, badreleglil commented on src/features/TreegeConsumer/TreegeConsumer.tsx
> +  renderInput,
faute d’inattention my bad

2024-04-04 14:48 UTC, badreleglil commented on src/components/Inputs/Select/Select.tsx
> +    // eslint-disable-next-line
A cette endroit on est obliger d'avoir un component did mount donc un useEffect sans dépendance

2024-04-04 14:58 UTC, badreleglil commented on src/components/Inputs/DynamicSelect/DynamicSelect.tsx
> +  const checkIfObjectAsKey = (obj: unknown, key: string) => {
`safeGetObjectValueByKey` c'est pas mal

2024-04-04 15:00 UTC, badreleglil commented on src/features/TreegeConsumer/TreegeConsumer.tsx
> +  jsonInitialValues?: JsonFormValue[];
Jsuis plus pour carrément supprimer initialValues qui n'est plus utilisé

2024-04-04 15:01 UTC, badreleglil commented on src/features/TreegeConsumer/TreegeConsumer.tsx
> +  jsonInitialValues?: JsonFormValue[];
et renommer `jsonInitialValues` par `initialValues`

2024-04-04 15:09 UTC, badreleglil commented on src/components/Inputs/BooleanField/BooleanField.tsx
> +  handleFormValue?(dataAttribute: ChangeEventField): void;
Le onChange me gene car pour certain champs ce n'est pas au onChange mais au onMount que la fonction est appelé

2024-04-04 15:16 UTC, MickaelAustoni commented on src/components/Inputs/BooleanField/BooleanField.tsx
> +  handleFormValue?(dataAttribute: ChangeEventField): void;
Il faudrait ajouter deux event callback alors onInit & onChange

2024-04-04 15:17 UTC, MickaelAustoni commented on src/features/TreegeConsumer/TreegeConsumer.tsx
> +  jsonInitialValues?: JsonFormValue[];
Ok ça me va

2024-04-04 15:24 UTC, MickaelAustoni commented on src/components/Inputs/Select/Select.tsx
> +    // eslint-disable-next-line
Obligé d'avoir un callback d'accord, mais tu peux le faire avec des dépendances. ComponentDidMount à pas été supprimer pour rien, c'est parce qu'un code avec des dépendance manquante à forcément des fails.

2024-04-05 09:20 UTC, badreleglil commented on src/components/Inputs/Select/Select.tsx
> +    // eslint-disable-next-line
Thanks pour le nouveau patern 💪🏽

```javascript
  // Trigger the onInit when the component is mounted
  useEffect(() => {
    if (isDecision) {
      onInitRef.current?.({ children, isDecision, isLeaf, name, type, value });
    }
  }, [children, isDecision, isLeaf, name, type, value]);

  // Update the onInitRef when the onInit changes
  useEffect(() => {
    onInitRef.current = onInit;
  }, [onInit]);
```

2024-04-05 09:38 UTC, MickaelAustoni approved these changes

2024-04-05 09:38 UTC, merged